### ISSUE TITLE
Need to use templating on st2kv

### ISSUE THREAD

**Issue by erenatas** [StackStorm/stackstorm-ha#102]
As you know, you cannot use templating on ```values.yaml```. I would like to put stackstorm-ha in the chart that I have written in ```requirements.yaml``` but I have a problem that I cannot pass on. I must hold some URL information such as DB or any kind of service URL but while doing that, I have to use {{ .Release.name }} while doing that and I cannot put release name  in values.yaml statically. 

I have figured a way but I can only do it by modifying ```secrets_st2kv.yaml``` which is to use a placeholder for the release name and then replace that placeholder with the release name on ```secrets_st2kv.yaml``` like this:

```
data:
  {{- $var := .Release.Name }}
  st2kv.yaml: {{ toYaml .Values.st2.keyvalue | replace "CHANGEFORRELEASE" $var | b64enc | quote }}
```

This works just fine, but if I do this, I will lose the ability to use stackstorm-ha as a dependency for my chart. I would like to hear your opinions about this. I really need this in someway and I would like not to break a good practice.

**Comment by armab** [comment]
Can you provide exact example construct of Helm values you'd like to see? 

----

Depending on specifics, there are some workarounds to support templating and we can add it for some fields in Values.

For reference, 
https://github.com/StackStorm/stackstorm-ha/blob/af48dff18dcd910ac59dbbb82638ac2dfbf386b9/templates/deployments.yaml#L1355

Use of `tpl` in `{{ tpl (.Values.st2chatops.image.tag | default .Chart.AppVersion) . }}` in Deployment template allowed me to provide the following templating for users in Helm values: 
https://github.com/StackStorm/stackstorm-ha/blob/af48dff18dcd910ac59dbbb82638ac2dfbf386b9/values.yaml#L338-L344

**Comment by erenatas** [comment]
> Can you provide exact example piece of Helm values you'd like to see with templates in it?
> 
> Depending on specifics, there are some workarounds to support templating and we can add it for some fields in Values.
> 
> For reference,
> https://github.com/StackStorm/stackstorm-ha/blob/af48dff18dcd910ac59dbbb82638ac2dfbf386b9/templates/deployments.yaml#L1355
> 
> Use of `tpl` in `{{ tpl (.Values.st2chatops.image.tag | default .Chart.AppVersion) . }}` in Deployment template allowed me to provide the following templating for users in Helm values:
> https://github.com/StackStorm/stackstorm-ha/blob/af48dff18dcd910ac59dbbb82638ac2dfbf386b9/values.yaml#L338-L344

Here is an example:

```
  keyvalue:
    - name: xxx_redis_ipv4
      scope: st2kv.system
      secret: false
      encrypted: false
      value: {{ .Release.Name }}-xxx-redis-ha-client
```

I need the templating especially for URLs, because everytime there is a new different deployment, release names also change. That 's why I have thought of a solution like I told you.

```
# values.yaml

...
  keyvalue:
    - name: xxx_redis_ipv4
      scope: st2kv.system
      secret: false
      encrypted: false
      value: CHANGEFORRELEASE-xxx-redis-ha-client
```

```
# secrets_st2kv.yaml

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-st2-kv
  annotations:
    description: Key/Value pairs to save in StackStorm's datastore
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    support: {{ template "supportMethod" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- $var := .Release.Name }}
  st2kv.yaml: {{ toYaml .Values.st2.keyvalue | replace "CHANGEFORRELEASE" $var | b64enc | quote }}

```
