### ISSUE TITLE
Add custom attributes to third party chart dependencies

### ISSUE THREAD

**Issue by stefangusa** [StackStorm/stackstorm-ha#124]
First of all, if the `rabbitmqErlangCookie`([RabbitMQ clustering docs](https://www.rabbitmq.com/clustering.html)) is not fixed and does not overwrites the default value in `rabbitmq-ha` chart where it is computed randomly at each apply, the RabbitMQ functioning is altered if the PVC are not deleted at each purge (my case but also found some similar issues). So I suggest overwriting this value in the `stackstorm-ha` chart.

In addition, I suggest the possibility of overwriting the `rabbitmqMemoryHighWatermark` [RabbitMQ memory alarm docs](https://www.rabbitmq.com/memory.html) as the provided value in the `rabbitmq-ha` chart might frequently be not enough.

Lastly, I think the `resources` attribute should be included both for `rabbitmq-ha` and `mongodb-ha`.

**Comment by armab** [comment]
You can already overwrite all Helm values for the sub-chart/dependency by using custom Helm values yaml file that's possible to pass to helm install/upgrade. In fact, that's the best way to keep custom settings.


Here is an example from our internal use:
```
stackstorm-ha:
  ##
  ## RabbitMQ HA configuration (3rd party chart dependency)
  ##
  ## For values.yaml reference:
  ## https://github.com/helm/charts/tree/master/stable/rabbitmq-ha
  ##
  rabbitmq-ha:
    # Improves RabbitMQ (re)deployment stability around Mnesia storage failures with the price of reduced availability
    # See https://github.com/helm/charts/pull/8767
    podManagementPolicy: Parallel
    # Recommended to pin erlangCookie during the cluster upgrades
    # See https://github.com/helm/charts/blob/master/stable/rabbitmq-ha/README.md#upgrading-the-chart
    rabbitmqErlangCookie: 4E6BbCHcgESBZZowQ8xEy0bedXFK6ZZz
```

I'd argue that the proposed defaults in #125 is something that's required or would be useful for everyone consuming `stackstorm-ha` chart, and so overriding settings per custom use is more encouraged.
