### ISSUE TITLE
Not able to install pack

### ISSUE THREAD

**Issue by manisha-tanwar** [StackStorm/stackstorm-ha#128]
Hi, I've been trying to install pack using these links on a single node K8 cluster.
https://github.com/StackStorm/st2packs-dockerfiles/
https://github.com/stackstorm/stackstorm-ha

Stackstorm is installed successfully with default dashboard but when I tried to build custom pack and helm upgrade it's not working.

Here is my stackstorm pack dir and image Dockerfile:

```
/home/manisha.tanwar/st2packs-dockerfiles # ll st2packs-image/packs/st2_chef/
total 28
drwxr-xr-x. 4 manisha.tanwar domain users 4096 Apr 28 16:11 actions
drwxr-xr-x. 2 manisha.tanwar domain users 4096 Apr 28 16:11 aliases
-rwxr-xr-x. 1 manisha.tanwar domain users  211 Apr 28 16:11 pack.yaml
-rwxr-xr-x. 1 manisha.tanwar domain users   65 Apr 28 16:11 README.md
-rwxr-xr-x. 1 manisha.tanwar domain users  293 Apr 28 17:47 requirements.txt
drwxr-xr-x. 2 manisha.tanwar domain users 4096 Apr 28 16:11 rules
drwxr-xr-x. 2 manisha.tanwar domain users 4096 Apr 28 16:11 sensors
```

 /home/manisha.tanwar/st2packs-dockerfiles # cat st2packs-image/Dockerfile
```
ARG PACKS="file:///tmp/stackstorm-st2"
FROM stackstorm/st2packs:builder AS builder

COPY packs/st2_chef /tmp/stackstorm-st2/
RUN ls -la /tmp/stackstorm-st2
RUN git config --global http.sslVerify false

# Install custom packs
RUN /opt/stackstorm/st2/bin/st2-pack-install ${PACKS}

###########################
# Minimize the image size. Start with alpine:3.8,
# and add only packs and virtualenvs from builder.
FROM stackstorm/st2packs:runtime
````

Image is created using command
`docker build -t st2_chef:v0.0.2 st2packs-image`

And then I changed values.yaml as below:
```
  packs:
    configs:
      packs.yaml: |
        ---
        # chef pack
    image:
      name: st2_chef
      tag: 0.0.1
      pullPolicy: Always
```

And run 
`helm upgrade <release-name>.`
but it doesn't show anything on dashboard as well as cmd.

Please help, We are planning to upgrade to Stackstorm HA from standalone stackstorm and I need to get POC done for that.

Thanks in advance!!

**Comment by arms11** [comment]
Did you try to delete the st2api pod after helm upgrade? Please try that and see if that does the trick.

**Comment by manisha-tanwar** [comment]
Thanks for quick response @arms11 

Tried deleting both api pods but no luck.. 

```
# kubectl get pods | grep api
eponymous-macaw-job-st2-apikey-load-fbldk                     0/1     Completed   0          150m
eponymous-macaw-st2api-6c656474f-nsrxc                        1/1     Running     2          3h3m
eponymous-macaw-st2api-6c656474f-r29nj                        1/1     Running     1          3h3m
ironic-zebra-job-st2-apikey-load-hjqms                        0/1     Completed   0          8d
left-seahorse-job-st2-apikey-load-8vpd2                       0/1     Completed   0          8d

kubectl delete pod eponymous-macaw-st2api-6c656474f-nsrxc
pod "eponymous-macaw-st2api-6c656474f-nsrxc" deleted
kubectl delete pod eponymous-macaw-st2api-6c656474f-r29nj
pod "eponymous-macaw-st2api-6c656474f-r29nj" deleted

# kubectl get pods | grep api
eponymous-macaw-job-st2-apikey-load-fbldk                     0/1     Completed   0          152m
eponymous-macaw-st2api-6c656474f-9bwp5                        1/1     Running     0          61s
eponymous-macaw-st2api-6c656474f-s92ff                        1/1     Running     0          110s
ironic-zebra-job-st2-apikey-load-hjqms                        0/1     Completed   0          8d
left-seahorse-job-st2-apikey-load-8vpd2                       0/1     Completed   0          8d
```
I'm not even sure if I installed it correctly, do you see anything wrong in my installation?

**Comment by arms11** [comment]
Sorry to hear that...

I had to delete api pod, webpod and actionrunner pod at one point to make sure it takes the Jenkins pack I tried to install. Unfortunately its trial/error and good thing about K8s is i can delete and it will pull the image. Please make sure image is pushed to the registry. Also, did you try to go to api pod and checked the filesystem where normally the pack gets installed? Just curious if it is placed there to begin with. 

Here is what my cluster looks like in AWS
```
 kubectl get pods
NAME                                                 READY   STATUS      RESTARTS   AGE
etcd-cluster-6xtlzhkx64                              1/1     Running     0          22d
etcd-cluster-rqzbzgvhmr                              1/1     Running     0          22d
etcd-cluster-wbwst6tt8l                              1/1     Running     0          22d
st2ha-etcd-operator-etcd-operator-5b689dc886-jh7ls   1/1     Running     2          22d
st2ha-job-st2-apikey-load-kknzl                      0/1     Completed   0          22d
st2ha-job-st2-key-load-jcs4r                         0/1     Completed   0          22d
st2ha-job-st2-register-content-h29kt                 0/1     Completed   0          22d
st2ha-mongodb-ha-0                                   1/1     Running     0          23d
st2ha-rabbitmq-ha-0                                  1/1     Running     0          22d
st2ha-rabbitmq-ha-1                                  1/1     Running     0          22d
st2ha-rabbitmq-ha-2                                  1/1     Running     0          22d
st2ha-st2actionrunner-7d8f876bf7-zf5qv               1/1     Running     0          23d
st2ha-st2api-56d76d997f-gh8nj                        1/1     Running     44         22d
st2ha-st2auth-787574bfcf-ttp9f                       1/1     Running     0          23d
st2ha-st2client-6fc47f9985-bbzq7                     1/1     Running     0          23d
st2ha-st2garbagecollector-8585f7f6c4-l88jp           1/1     Running     22         23d
st2ha-st2notifier-5db97c65fd-qc2fd                   1/1     Running     0          23d
st2ha-st2rulesengine-6bffcc668c-6djpw                1/1     Running     0          23d
st2ha-st2scheduler-5755898679-kn4nc                  1/1     Running     0          22d
st2ha-st2sensorcontainer-7b68dcdd5c-tfsns            1/1     Running     0          23d
st2ha-st2stream-6d55585575-9gfbw                     1/1     Running     22         23d
st2ha-st2timersengine-744887dfb4-fc4dk               1/1     Running     25         23d
st2ha-st2web-757b4c98bc-mdwc2                        1/1     Running     0          23d
st2ha-st2workflowengine-66f6598cb9-qsnhh             1/1     Running     23         23d
```

**Comment by manisha-tanwar** [comment]
Is it mandatory to push image to docker registary? Also would it be possible for you to show content inside values.yaml for helm. Followed your jenkins pack installation at
 https://github.com/arms11/stackstorm-jenkins

and seems like my pack creation is good enough not sure about values.yaml though.


Also tried delete all these pods but no luck.

**Comment by arms11** [comment]
Here is what my packs section in Values.yaml looks like...

```
packs:
    # Custom StackStorm pack configs. Each record creates a file in '/opt/stackstorm/configs/'
    # https://docs.stackstorm.com/reference/pack_configs.html#configuration-file
    configs:
      core.yaml: |
        ---
        # example core pack config yaml

    # Custom packs image settings. The repository, name, tag and pullPolicy for this image
    # are specified below.
    image:
      # Uncomment the following block to make the custom packs image available to the necessary pods
      repository: arms11
      name: st2packs
      tag: "1.0"
      pullPolicy: Always
      # Optional name of the imagePullSecret if your custom packs image is hosted by a private Docker registry behind the auth
      #pullSecret: st2packs-auth
```
