### ISSUE TITLE
Rearrange "secrets" in Helm values

### ISSUE THREAD

**Issue by armab** [StackStorm/stackstorm-ha#14]
Currently in Helm `values.yaml` for this chart there is a dedicated `secrets` section holding values for data like st2 username/password, SSL certs, SSH keys and so on.

~We wanted to move it to dedicated `secrets.yaml` when it gets implemented in Helm (https://github.com/kubernetes/helm/issues/2196).~ (now closed)

**Update:** We'll need to just obsolete dedicated `secrets` block and merge it with all other sections as any official Helm chart does without dedicated sub-section weirdness.

https://github.com/StackStorm/stackstorm-enterprise-ha/blob/95fe6bb5f0d76ef772ad3f4391ff5cd3e00d1d86/values.yaml#L82-L100

~Feedback needed: which approach/way looks better and friendlier to you?~

**Comment by mickmcgrath13** [comment]
Why not separate out the secrets to their respective services rather than aggregating them.  
i.e.
```
serviceA:
  secrets:
    foo: a
serviceB:
  secrets:
    bar: b
```
instead of:
```
secrets:
  serviceA:
    foo: a
  serviceB:
    bar: b
```
?

This would still work well with a separate `secrets.yaml` file

**Comment by armab** [comment]
It all depends and on what's the future of https://github.com/helm/helm/issues/2196 and where it'll go or whether it'll get implemented anytime.

Looking back, feels like going with YOLO approach and planning for "now":

```
st2:
  username: st2admin
  password: ***
```
what's used by the other official Helm charts was a more natural way comparing to:
```
secrets:
  st2:
    username: st2admin
    password: ***
```
or
```
st2:
  secrets:
    username: st2admin
    password: ***
```
