### ISSUE TITLE
Does ST2 Web Ingress support not only "/"?

### ISSUE THREAD

**Issue by wantdrink** [StackStorm/stackstorm-ha#145]
Hi there,
We are testing installing 2 stackstorm (1 active and the other for backup) in the same k8s cluster. The helm release name is 'st1' and 'st2'
.
I enabled the ingress and try to use path rewrite and hope to access them with /st1 /st2.
"stackstorm.dev.com" is our dev F5 VIP with DNS resolvable.

```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: stackstorm.dev.com
      paths:
        - path: /st1(/|$)(.*)
          serviceName: st1-st2web
          servicePort: 80

```

Finally I found that access https://stackstorm.dev.com/st1/ (the tail '/' should not be omitted) and try to login.I can see the home page, but login will be redirected to:

`Request URL: https://stackstorm.dev.com/auth/tokens`

context 'st1' was lost.

Do we support the URL rewrite in st2-web like grafana? If not we can only access the ingress from that VIP with "/" for only one of those instances.

**Comment by armab** [comment]
The Helm chart just provides the templating around the K8s Ingress (https://kubernetes.io/docs/concepts/services-networking/ingress/):
https://github.com/StackStorm/stackstorm-ha/blob/5575afcc8594b21e90648ae78f27b2c2ec254ee7/templates/ingress.yaml#L24-L44

As I understand the behavior and rewrite mechanisms might look different depending on K8s Ingress controller you configure (https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/).

So worth debugging further down the path.

Another point to mention, - after the Ingress you hit the nginx st2web. So that's another place to look at. Here is how the config looks like: https://github.com/StackStorm/st2/blob/master/conf/nginx/st2.conf

If you'll find the solution for your problem, - please don't forget to share it in the issue.

**Comment by wantdrink** [comment]
Thanks @armab .
Based on [https://github.com/StackStorm/st2/blob/master/conf/nginx/st2.conf](url) if change the requirement from "access different context path to reach different stackstorm HA instances" to "just change the context path for the only one", it could be solved as:
  ```
annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: stackstorm.dev.com
      paths:
        - path: /st1(/|$)(.*)
          serviceName: st1-st2web
          servicePort: 80
        - path: /auth(/|$)(.*)
          serviceName: st1-st2auth
          servicePort: 9100
        - path: /api(/|$)(.*)
          serviceName: st1-st2api
          servicePort: 9101
        - path: /stream(/|$)(.*)
          serviceName: st1-st2stream
          servicePort: 9102
```

But for the original requirement we still need to dig into the code. The web UI access api/stream/auth directly with https://[api/stream/auth] without considering the context path.
So maybe it's hard to access different HA instances with the rewrite mechenizm.

**Comment by moonrail** [comment]
Hi @wantdrink 
I just stumbled upon this issue.

The solution is to configure st2web.

In https://github.com/StackStorm/stackstorm-ha/pull/165 this chart was extended to give you the possibility to set the configuration of st2web.
It was released in https://github.com/StackStorm/stackstorm-ha/releases/tag/v0.52.0.
Here is the description in `values.yaml` how to use it: https://github.com/StackStorm/stackstorm-ha/blob/89be5cdc65beba7155140594118dbda1fef23356/values.yaml#L250

For your use-case the variables could be e.g.:
```yaml
(...)
st2web:
  (...)
  config: |
    'use strict';

    /* global angular */
    angular.module('main')
      .constant('st2Config', {

        hosts: [
          {
            name: 'test',
            url: 'https://stackstorm.dev.com/st1/api',
            auth: 'https://stackstorm.dev.com/st1/auth',
            stream: 'https://stackstorm.dev.com/st1/stream',
          }
        ]

      });
```

**Comment by cognifloyd** [comment]
@wantdrink does https://github.com/StackStorm/stackstorm-ha/issues/145#issuecomment-811918925 resolve your issues?

**Comment by cognifloyd** [comment]
@wantdrink I'm going to close this. Please reopen if you still have a question about this.

**Comment by wantdrink** [comment]
Thanks a lot @moonrail & @cognifloyd , that really helps!

**Comment by wantdrink** [comment]
@moonrail, Furthermore in the latest 0.8.0 the values.yaml configuration looks like:
```
st2web:  
  replicas: 2
  ......
  # mount extra volumes on the st2web pod(s) (primarily useful for k8s-provisioned secrets)
  ## Note that Helm templating is supported in 'mount' and 'volume'
  extra_volumes: []
    # see examples under st2workflowengine.extra_volumes
  # User-defined st2web config with custom settings to replace default config.js
  # See https://github.com/StackStorm/st2web#connecting-to-st2-server for more info
  # config: |
  #  // see https://github.com/StackStorm/st2web/blob/master/config.js
  # postStartScript is optional. It has the contents of a bash script.
  # k8s will run the script in the st2 container in parallel with the ENTRYPOINT.
  # The pod will not be marked as "running" until this script completes successfully.
  # see: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
  postStartScript: ""
```

So what we have to do is to change it as:

```
st2web:  
  replicas: 2
  ......
  # mount extra volumes on the st2web pod(s) (primarily useful for k8s-provisioned secrets)
  ## Note that Helm templating is supported in 'mount' and 'volume'
  extra_volumes:
    config: |
      'use strict';
  
      /* global angular */
      angular.module('main')
        .constant('st2Config', {
  
          hosts: [
            {
              name: 'test',
              url: 'https://stackstorm.dev.com/st1/api',
              auth: 'https://stackstorm.dev.com/st1/auth',
              stream: 'https://stackstorm.dev.com/st1/stream',
            }
          ]
  
        });   
  postStartScript: ""
```

and in the ingress still needs to configure rewrite below? Thanks a lot.
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: stackstorm.dev.com
      paths:
        - path: /st1(/|$)(.*)
          serviceName: st1-st2web
          servicePort: 80
```

**Comment by wantdrink** [comment]
@moonrail, Furthermore in the latest 0.8.0 what we have to do is to change it as:

```
st2web:  
  replicas: 2
  ......
  extra_volumes: []
    # see examples under st2workflowengine.extra_volumes
  # User-defined st2web config with custom settings to replace default config.js
  # See https://github.com/StackStorm/st2web#connecting-to-st2-server for more info

  # config: |
  #  // see https://github.com/StackStorm/st2web/blob/master/config.js
  config: |
    'use strict';

    /* global angular */
    angular.module('main')
      .constant('st2Config', {

        hosts: [
          {
            name: 'stackstorm.dev.com',
            url: 'https://stackstorm.dev.com/ss1/api',
            auth: 'https://stackstorm.dev.com/ss1/auth',
            stream: 'https://stackstorm.dev.com/ss1/stream',
          }
        ]

      });

  # postStartScript is optional. It has the contents of a bash script.
  # k8s will run the script in the st2 container in parallel with the ENTRYPOINT.
  # The pod will not be marked as "running" until this script completes successfully.
  # see: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
  postStartScript: ""
  ......
```

and in the ingress still needs to configure rewrite below? Thanks a lot.
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: stackstorm.dev.com
      paths:
        - path: /st1(/|$)(.*)
          serviceName: st1-st2web
          servicePort: 80
```
