### ISSUE TITLE
The node was low on resource: ephemeral-storage. Container st2actionrunner was using 82Ki, which exceeds its request of 0

### ISSUE THREAD

**Issue by manisha-tanwar** [StackStorm/stackstorm-ha#170]
Hi Team,

I'm getting below error for almost all the pods :

```
The node was low on resource: ephemeral-storage 
The node was low on resource: ephemeral-storage. Container st2client was using 51Ki, which exceeds its request of 0.
The node was low on resource: ephemeral-storage. Container st2actionrunner was using 82Ki, which exceeds its request of 0
```

I tried to set it for 1 of the pod to (request 50Mi & limit 100Mi) but then it says it's not sufficient. Why is it giving me this error suddenly(I added few more packs today).

Is it possible to use persistence storage for all configuration, if yes what all files do I need to change.

Any help would be appreciated.

Thanks,
Manisha Tanwar

**Comment by arms11** [comment]
I am not familiar with this error. But, doing the search, I came across below and hope that helps. https://stackoverflow.com/questions/59906810/the-node-was-low-on-resource-ephemeral-storage 
Also, not sure if you have metrics/instrumentation in place to help you see if there are disk space issues. That could explain "sudden" nature of the occurrence.

**Comment by manisha-tanwar** [comment]
Yeah it says:

> Pods that use emptyDir volumes without storage quotas will fill up this storage.

I checked and each pod is taking ~ 1GB or st2-virtualenvs-vol. Is it possible to replace all EmptyDir to PVC volumeMount?

**Comment by manisha-tanwar** [comment]
ok so I edited both deployments.yaml & jobs.yaml from:
```
     volumes:
        - name: st2-packs-vol
          emptyDir: {}
        - name: st2-virtualenvs-vol
          emptyDir: {}
```
to:
```
      volumes:
        - name: st2-packs-vol
          persistentVolumeClaim:
            claimName: st2-packsvol
        - name: st2-virtualenvs-vol
          persistentVolumeClaim:
            claimName: st2-virtualenvs
```

and created both PVCs manually. Now it seems like consuming pvc and not ephemeral storage anymore.
