### ISSUE TITLE
Feature Request: Allow configuration of logging to GELF and/or logfmt + custom formats

### ISSUE THREAD

**Issue by cydergoth** [StackStorm/stackstorm-ha#269]
Basically, expose the python logging configuration in the helm chart and provide pre-canned examples for popular formats

**Comment by cognifloyd** [comment]
@cydergoth I created #276 to make it possible to provide custom logging config.

To use that, you create a ConfigMap (not maintained by this chart) that includes your `logging.conf` file.
Then you add that configmap to the deployments with something like this:
```yaml
st2api:
  extra_volumes:
    - &logging_vol
      name: custom-logging-conf
      mount:
        mountPath: /etc/st2/logging.docker.conf
        subPath: logging.docker.conf
      volume:
        configMap:
          name: st2-logging-conf
st2auth:
  extra-volumes:
    - *logging_vol
st2stream:
  extra-volumes:
    - *logging_vol
# etc. same for other st2* services.
st2actionrunner:
  - <<: *logging_vol
    mount:
      mountPath: /etc/st2/logging.docker.conf
      subPath: logging.audit.conf
```

Note I have a different logging conf file for st2actionrunner versus the rest of the services.
Would something like this work for you?
