### ISSUE TITLE
K8s Ingress Controller

### ISSUE THREAD

**Issue by armab** [StackStorm/stackstorm-ha#6]
> Moved from https://github.com/StackStorm/k8s-st2/issues/31

As part of templating Helm Charts, we'll need a K8s Ingress controller (https://kubernetes.io/docs/concepts/services-networking/ingress/) to allow user configuring inbound access to StackStorm Web UI/APIs from the outside world and have more granular configuration comparing to `LoadBalancer` type.

## The Plan

Per https://github.com/StackStorm/stackstorm-ha/pull/44#issuecomment-459060262 discussion we want to:
1) Expose Ingress controller settings via Helm `values.yaml` to allow users to configure the SSL/TLS negotiation layer on their own (optional).
2) Change `st2web` Docker image so it will respond on HTTP by default (currently HTTPS).

https://github.com/StackStorm/stackstorm-enterprise-ha/blob/d5e34fc28e820e39097d5eaac7dcadcc4a481f2b/values.yaml#L204-L205

https://github.com/StackStorm/stackstorm-enterprise-ha/blob/d5e34fc28e820e39097d5eaac7dcadcc4a481f2b/templates/ingress.yaml#L1

## Resources
- https://kubernetes.io/docs/concepts/services-networking/ingress/
- https://github.com/kubernetes/ingress-nginx
- https://kubernetes.github.io/ingress-nginx/ingress-controller-catalog/
- https://blog.getambassador.io/kubernetes-ingress-nodeport-load-balancers-and-ingress-controllers-6e29f1c44f2d
- https://akomljen.com/kubernetes-nginx-ingress-controller/

**Comment by armab** [comment]
Overview of different types K8s Service types and when to use what:
https://medium.com/@pczarkowski/kubernetes-services-exposed-86d45c994521

**Comment by mosn** [comment]
Providing my feedback since this one is still open.
with changes to `values.yaml` it was easy to expose service behind `st2web` to outside.

```
  service:
    type: "LoadBalancer"
    hostname: "example.domain.com"
```

I can also wish for a way to set Ingress controller inside `values.yaml`  but I am not sure how feasible that is considering all services depending on st2web load balancing capability.  

```
ingress:
  enabled: true
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/issuer:  my-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/configuration-snippet: |\

  hosts:
    - example.domain.com
  tls:
    - secretName: tls-secret
      hosts:
        - example.domain.com
```

**Comment by armab** [comment]
Thank you very much @mosn, that's definitely useful!

Per https://github.com/StackStorm/stackstorm-ha/pull/44#issuecomment-459060262 discussion we definitely want to expose Ingress controller settings via Helm `values.yaml` to allow users to configure the SSL/TLS negotiation layer on their own (optional). To make it more consistent and efficient, `st2web` will go HTTP by default (currently HTTPS).

Yes, st2web uses nginx under the hood and adding Ingress controller will add another proxy layer on top, but I can't think of anything else easy & usable, as st2web exposes StackStorm Web UI apart of APIs.

**Comment by mosn** [comment]
As an alternative, We can also look into the possibility of using existing Ingress Controller in the cluster. Example with `cert-manager` something like

 ===WARNING WORK IN PROGRESS DONT USE=== 

Install cert-manager 
```
git clone https://github.com/jetstack/cert-manager
git checkout v0.2.3
helm install --name cert-manager contrib/charts/cert-manager --set ingressShim.extraArgs='{--default-issuer-name=letsencrypt-prod,--default-issuer-kind=ClusterIssuer}' --set ingressShim.enabled=false --namespace kube-system
kubectl -n kube-system get pods
```

Add an ingress-controller 
```
helm install --name ingress-my-test-app stable/nginx-ingress --set rbac.create='true'
```

Configure issuer (cluster issuer)
```
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    # The ACME server URL
    server: https://acme-v01.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: your.name@example.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-key
    # Enable HTTP01 validations
    http01: {}
```

Manually generate a certificate resource 
```
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: stackstorm-st2web-enterprise
  namespace: default
spec:
  secretName: stackstorm-st2web-enterprise
  commonName: st.example.com
  dnsNames:
  - st2.example.com
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - st2.example.com
```

Configure st2web to with the ingress controller 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stackstorm-st2web-enterprise
  namespace: default
  annotations:
    certmanager.k8s.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: st.node.rpt.sh
      http:
        paths:
          - backend:
              serviceName: stackstorm-st2web-enterprise
              servicePort: 30677
            path: /
  tls:
    - hosts:
        - st.node.rpt.sh
      secretName: stackstorm-st2web-enterprise
```


I can issue the certificate this way just fine but still unable to connect to st2web for some reason.
